version: '3.9'

networks:
  dev:
    driver: bridge

services:
  api:
    build: .
    container_name: fastfood_tickets_api
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5002
    depends_on:
      database:
        condition: service_healthy
    networks:
      - dev