version: '3.9'

networks:
  dev:
    driver: bridge

services:
  database:
    image: postgres:latest
    container_name: fastfood_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - fastfood_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5
    networks:
      - dev

  api:
    build: .
    container_name: fastfood_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Default=Server=database;Database=postgres;Username=postgres;Password=docker;Port=5432
    depends_on:
      database:
        condition: service_healthy
    networks:
      - dev

volumes:
  fastfood_data:
    name: "fastfood_data"