apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-pv-volume2
  labels:
    type: local
spec:
  storageClassName: local-pgdata2
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/pgdata"