apiVersion: v1
kind: ConfigMap
metadata:
  name: fast-food-tickets-api-configmap
  labels:
    app: fast-food-tickets-api-configmap
data:
  ASPNETCORE_ENVIRONMENT: "#{ENVIRONMENT}#"
  ASPNETCORE_HTTP_PORTS: "8080"
  OrdersApiSettings__BaseAddress: "#{ORDERS_API_URL}#"
