apiVersion: v1
kind: Secret
metadata:
  name: fast-food-api-secret
  labels:
    app: fast-food-api-secret
type: Opaque
stringData:
  ConnectionStrings__Default: "Server=#{DB_ENDPOINT}#;Database=#{DB_NAME}#;Username=#{DB_USERNAME}#;Password=#{DB_PASSWORD}#;Port=#{DB_PORT}#"
