apiVersion: v1
kind: Secret
metadata:
  name: fast-food-tickets-api-secret
  labels:
    app: fast-food-tickets-api-secret
type: Opaque
stringData:
  AmazonSettings__AccessKey: "#{AWS_ACCESS_KEY_ID}#"
  AmazonSettings__SecretKey: "#{AWS_SECRET_ACCESS_KEY}#"
  AmazonSettings__SessionToken: "#{AWS_SESSION_TOKEN}#"
